school-web-rebirth/src/main/java/fr/wati/school/web/rebirth/controller/view/LoginController.java
/**
 * 
 */
package fr.wati.school.web.rebirth.controller.view;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ResourceLoader;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import fr.wati.school.web.rebirth.commons.Breadcrumbs;
import fr.wati.school.web.rebirth.utils.ImprovedMustacheTemplateLoader;

/**
 * @author Rachid Ouattara
 * 
 */
@Controller
public class LoginController extends AbstractPageController {

	@Autowired
    private ImprovedMustacheTemplateLoader improvedMustacheTemplateLoader;
	
	@Autowired
	private ResourceLoader resourceLoader;

	@RequestMapping(value = "/login")
	public ModelAndView login(@RequestParam(value="error",defaultValue="false",required=false) boolean error,HttpSession httpSession) {

		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("layouts/login");
		super.processModelAndView(modelAndView);
		modelAndView.addObject("pageContent", "pages/login");
		if(error){
			modelAndView.addObject("error", true);
			String exeptionMessage=null;
			if(httpSession!=null){
				if(httpSession.getAttribute("SPRING_SECURITY_LAST_EXCEPTION") instanceof Exception){
					exeptionMessage=((Exception)httpSession.getAttribute("SPRING_SECURITY_LAST_EXCEPTION")).getMessage();
					modelAndView.addObject("errorMessage", exeptionMessage);
				}
				
			}
		}
		improvedMustacheTemplateLoader.getIncludedTemplatePath().get().put("pageContent", "pages/login");
		return modelAndView;
	}

	
	@RequestMapping(value="/loginfailed", method = RequestMethod.GET)
	public String loginerror(ModelAndView modelAndView) {
		modelAndView.addObject("error", "true");
		modelAndView.addObject("errorMessage", "true");
		return "login";
 
	}
	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * fr.wati.school.web.rebirth.controller.AbstractPageController#getTitle()
	 */
	@Override
	public String getTitle() {
		return "Login page";
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * fr.wati.school.web.rebirth.controller.AbstractPageController#getDescription
	 * ()
	 */
	@Override
	public String getDescription() {
		return "School WebAPP";
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see fr.wati.school.web.rebirth.controller.AbstractPageController#
	 * getInline_scripts()
	 */
	@Override
	public String getInline_scripts() {
		return "views/assets/scripts/login.js";
	}

	/* (non-Javadoc)
	 * @see fr.wati.school.web.rebirth.controller.AbstractPageController#getResourceLoader()
	 */
	@Override
	public ResourceLoader getResourceLoader() {
		return resourceLoader;
	}

	/* (non-Javadoc)e
	 * @see fr.wati.school.web.rebirth.controller.AbstractPageController#getContent()
	 */
	@Override
	public String getContent() {
		return "views/pages/login";
	}

	@Override
	public Breadcrumbs getBreadcrumbs() {
		return null;
	}

	@Override
	public String[] getScripts() {
		return null;
	}

	@Override
	public String[] getIe_scripts() {
		return null;
	}

	/* (non-Javadoc)
	 * @see fr.wati.school.web.rebirth.controller.AbstractPageController#getStyles()
	 */
	@Override
	public String[] getStyles() {
		return null;
	}
}

school-web-rebirth/src/main/webapp/WEB-INF/views/layouts/default.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">
	<jsp:include
	page="/WEB-INF/views/layouts/partials/_shared/_template/header.jsp"/>
	<body class="no-skin">
	<jsp:include
	page="/WEB-INF/views/layouts/partials/_shared/topbar.jsp"/>

		<div class="main-container" id="main-container">
		 <script type="text/javascript">
		 try{ace.settings.check('main-container' , 'fixed')}catch(e){}
		 </script>
		 <div class="main-container-inner">
		<jsp:include
			page="/WEB-INF/views/layouts/partials/_shared/sidenav.jsp"/>
			<div class="main-content">
				<jsp:include
					page="/WEB-INF/views/layouts/partials/default/breadcrumbs.jsp"/>
				<div class="page-content">
					<jsp:include
				page="/WEB-INF/views/layouts/partials/_shared/settings.jsp"/>
					<!-- {{^page.no-header}}{{!if no such thing as "no-header", then print header}} -->
					<div class="page-header">
						<h1>${page.title} 
							<c:if test="${not empty page.description}">
    							<small><i class="icon-double-angle-right"></i> ${page.description}</small>
							</c:if>
							
						</h1>
					</div><!--/.page-header-->
					<!-- {{/page.no-header}} -->

					<div class="row">
					 <div class="col-xs-12">
<!-- PAGE CONTENT BEGINS -->
	<jsp:include page="/WEB-INF/views/${page.content}.jsp"></jsp:include>
<!-- PAGE CONTENT ENDS -->
					 </div><!--/.col-->
					</div><!--/.row-->

				</div><!--/.page-content-->

			</div><!--/.main-content -->
			
		 </div><!--/.main-container-inner-->

		 <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
			<i class="icon-double-angle-up icon-only bigger-110"></i>
		 </a>
		</div><!--/.main-container-->
		
		<jsp:include
	page="/WEB-INF/views/layouts/partials/_shared/_template/footer.jsp"/>
	
	</body>
</html>

school-web-rebirth/src/main/webapp/WEB-INF/views/layouts/empty.jsp
<!DOCTYPE html>
<html lang="en">
	{{> layout._template.header}}

	<body>
	{{> layout.topbar}}

		<div class="main-container" id="main-container">
		 <script type="text/javascript">
		 try{ace.settings.check('main-container' , 'fixed')}catch(e){}
		 </script>
		 <div class="main-container-inner">

		 {{> layout.sidenav}}

			<div class="main-content">
				<div class="page-content">
					<div class="row">
					 <div class="col-xs-12">
<!-- PAGE CONTENT BEGINS -->
{{> page.content }}
<!-- PAGE CONTENT ENDS -->
					 </div><!--/.col-->
					</div><!--/.row-->
				</div><!--/.page-content-->

			</div><!--/.main-content-->

			{{> layout.settings}}
		 </div><!--/.main-container-inner-->
		</div><!--/.main-container-->

		{{> layout._template.footer}}

	</body>
</html>

school-web-rebirth/src/main/webapp/WEB-INF/views/layouts/login.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">
<jsp:include
	page="/WEB-INF/views/layouts/partials/login/_template/header.jsp"/>

<body class="login-layout light-login">

	<div class="main-container">
		<div class="main-content">
			<div class="row">
				<div class="col-sm-10 col-sm-offset-1">
					<jsp:include page="/WEB-INF/views/${pageContent}.jsp"></jsp:include>
				</div>
				<!--/.col-->
			</div>
			<!--/.row-->
		</div>
	</div>
	<!--/.main-container-->

	<jsp:include
		page="/WEB-INF/views/layouts/partials/login/_template/footer.jsp"></jsp:include>

</body>
</html>