school-web-rebirth/src/main/java/fr/wati/school/web/rebirth/controller/view/LoginController.java
/**
 * 
 */
package fr.wati.school.web.rebirth.controller.view;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ResourceLoader;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import fr.wati.school.web.rebirth.commons.Breadcrumbs;
import fr.wati.school.web.rebirth.utils.ImprovedMustacheTemplateLoader;

/**
 * @author Rachid Ouattara
 * 
 */
@Controller
public class LoginController extends AbstractPageController {

	@Autowired
    private ImprovedMustacheTemplateLoader improvedMustacheTemplateLoader;
	
	@Autowired
	private ResourceLoader resourceLoader;

	@RequestMapping(value = "/login")
	public ModelAndView login(@RequestParam(value="error",defaultValue="false",required=false) boolean error,HttpSession httpSession) {

		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("layouts/login");
		super.processModelAndView(modelAndView);
		modelAndView.addObject("pageContent", "pages/login");
		if(error){
			modelAndView.addObject("error", true);
			String exeptionMessage=null;
			if(httpSession!=null){
				if(httpSession.getAttribute("SPRING_SECURITY_LAST_EXCEPTION") instanceof Exception){
					exeptionMessage=((Exception)httpSession.getAttribute("SPRING_SECURITY_LAST_EXCEPTION")).getMessage();
					modelAndView.addObject("errorMessage", exeptionMessage);
				}
				
			}
		}
		improvedMustacheTemplateLoader.getIncludedTemplatePath().get().put("pageContent", "pages/login");
		return modelAndView;
	}

	
	@RequestMapping(value="/loginfailed", method = RequestMethod.GET)
	public String loginerror(ModelAndView modelAndView) {
		modelAndView.addObject("error", "true");
		modelAndView.addObject("errorMessage", "true");
		return "login";
 
	}
	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * fr.wati.school.web.rebirth.controller.AbstractPageController#getTitle()
	 */
	@Override
	public String getTitle() {
		return "Login page";
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * fr.wati.school.web.rebirth.controller.AbstractPageController#getDescription
	 * ()
	 */
	@Override
	public String getDescription() {
		return "School WebAPP";
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see fr.wati.school.web.rebirth.controller.AbstractPageController#
	 * getInline_scripts()
	 */
	@Override
	public String getInline_scripts() {
		return "views/assets/scripts/login.js";
	}

	/* (non-Javadoc)
	 * @see fr.wati.school.web.rebirth.controller.AbstractPageController#getResourceLoader()
	 */
	@Override
	public ResourceLoader getResourceLoader() {
		return resourceLoader;
	}

	/* (non-Javadoc)e
	 * @see fr.wati.school.web.rebirth.controller.AbstractPageController#getContent()
	 */
	@Override
	public String getContent() {
		return "views/pages/login";
	}

	@Override
	public Breadcrumbs getBreadcrumbs() {
		return null;
	}

	@Override
	public String[] getScripts() {
		return null;
	}

	@Override
	public String[] getIe_scripts() {
		return null;
	}

	/* (non-Javadoc)
	 * @see fr.wati.school.web.rebirth.controller.AbstractPageController#getStyles()
	 */
	@Override
	public String[] getStyles() {
		return null;
	}
}

school-web-rebirth/src/main/webapp/WEB-INF/views/layouts/partials/_shared/_template/fonts.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:if test="${site.remote_fonts}">
    		<link rel="stylesheet" href="${site.protocol}//fonts.googleapis.com/css?family=Open+Sans:400,300" />
</c:if>

<c:if test="${site.remote_fonts==false}">
    		<link rel="stylesheet" href="${path.assets}/css/ace-fonts.css" />
</c:if>

school-web-rebirth/src/main/webapp/WEB-INF/views/layouts/partials/_shared/_template/footer.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!-- basic scripts -->
<jsp:include
	page="/WEB-INF/views/layouts/partials/_shared/_template/jquery.jsp"/>

<script src="${path.assets}/js/bootstrap.min.js"></script>
<script src="${path.assets}/js/typeahead-bs2.min.js"></script>

<!-- page specific plugin scripts -->
<!-- {{!put IE only scripts here, currently we only use ExCanvas.js from time to time}} -->
<c:if test="${not empty page.ie_scripts}">
	<!--[if lte IE {{version}}]>
  <script src="{{{path.assets}}}/js/{{{file_name}}}"></script>
<![endif]-->
</c:if>

<c:if test="${not empty page.scripts}">
    		<c:forEach var="entry" items="${page.scripts}" >
				<script src="${path.assets}/js/${entry}"></script>
			</c:forEach>
</c:if>

<!-- ace scripts -->
<script src="${path.assets}/js/ace-elements.min.js"></script>
<script src="${path.assets}/js/ace.min.js"></script>


<!-- inline scripts related to this page -->
<c:if test="${not empty page.inline_scripts}">
    	<script type="text/javascript">
    		${page.inline_scripts}
    	</script>
</c:if>

school-web-rebirth/src/main/webapp/WEB-INF/views/layouts/partials/_shared/_template/header.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<head>
	<meta charset="utf-8" />
	<title>${page.title} - ${site.title}</title>
	<meta name="description" content="${page.description}" />

	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<!-- basic styles -->
	<link href="${path.assets}/css/bootstrap.min.css" rel="stylesheet" />
	

	<link rel="stylesheet" href="${path.assets}/css/font-awesome.min.css" />
	<!--[if IE 7]>
	  <link rel="stylesheet" href="${path.assets}/css/font-awesome-ie7.min.css" />
	<![endif]-->


	<!-- page specific plugin styles -->
	<c:if test="${not empty page.styles}">
    		<c:forEach var="entry" items="${page.styles}" >
				<link rel="stylesheet" href="${path.assets}/css/${entry}" />
			</c:forEach>
	</c:if>
	
	<!-- fonts -->
	<jsp:include
	page="/WEB-INF/views/layouts/partials/_shared/_template/fonts.jsp"/>
	
	<!-- ace styles -->
	<link rel="stylesheet" href="${path.assets}/css/ace.min.css" />
	<link rel="stylesheet" href="${path.assets}/css/ace-rtl.min.css" />
	<link rel="stylesheet" href="${path.assets}/css/ace-skins.min.css" />
	<!--[if lte IE 8]>
	  <link rel="stylesheet" href="${path.assets}/css/ace-ie.min.css" />
	<![endif]-->
	
	<!-- inline styles related to this page -->
	<!-- <style>
	.datepicker{ 
		z-index: 100000 !important;
	}
	
	</style> -->
	<c:if test="${not empty page.inline_styles}">
    	<style>
    		${page.inline_styles}
    	</style>
	</c:if>

	<!-- ace settings handler -->
	<script src="${path.assets}/js/ace-extra.min.js"></script>
	<!-- school Utils -->
	<script src="${path.assets}/js/utils.js"></script>
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="${path.assets}/js/html5shiv.js"></script>
	<script src="${path.assets}/js/respond.min.js"></script>
	<![endif]-->
	<script type="text/javascript">
        function doAjaxPost(divJQuerySelector, url) {

                    // get the form values
                    $.ajax({
                    	type: "POST",
                    	url: url,
                    	success: function(response){
                    				// we have the response
                    				$("#"+divJQuerySelector).html(response);
              					},
           				error: function(e){
             				alert('Error: ' + e);
           						}	
         			});
       }
    </script>

</head>

school-web-rebirth/src/main/webapp/WEB-INF/views/layouts/partials/_shared/_template/jquery.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:if test="${site.remote_jquery}">
	<!--[if !IE]> -->
<script src="${site.protocol}//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<!-- <![endif]-->
<!--[if IE]>
<script src="${site.protocol}//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->    		
</c:if>

<!--[if !IE]> -->
<script type="text/javascript">
 window.jQuery || document.write("<script src='${path.assets}/js/jquery.min.js'>"+"<"+"/script>");
</script>
<!-- <![endif]-->
<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='${path.assets}/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
	if("ontouchend" in document) document.write("<script src='${path.assets}/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>